name: build

on:
  push:

env:
  VCPKG_BINARY_SOURCES: 'clear;nuget,GitHub,readwrite'
  VCPKG_FEATURE_FLAGS: manifests,binarycaching

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: true
      matrix:
        build_type: [Debug, Release]

    steps:
    - uses: actions/checkout@v2
    - uses: seanmiddleditch/gha-setup-ninja@v3

    - uses: lukka/run-vcpkg@v10
      with:
        vcpkgGitCommitId: 078f3e51efd5ea6072d0ba28d11baa946519a2ce

    - name: CMake - Configure
      working-directory: build
      run: |
        cmake -G Ninja \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -DCMAKE_TOOLCHAIN_FILE="${VCPKG_ROOT//\\//}/scripts/buildsystems/vcpkg.cmake" \
          ../

    - name: CMake - Build
      working-directory: build
      run: |
        cmake --build . --config ${{ matrix.build_type }}


  registry-update:
    needs: build
    runs-on: windows-latest
    steps:
    - uses: PazerOP/vcpkg-registry-update@HEAD
      with:
        port-name: mh-stuff
        port-hash: ${{ env.GITHUB_SHA }}

