name: build

on:
  push:

env:
  VCPKG_BINARY_SOURCES: 'clear;nuget,GitHub,readwrite'
  VCPKG_FEATURE_FLAGS: manifests,binarycaching
  X_VCPKG_NUGET_ID_PREFIX: mh-glad2-gl

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: true
      matrix:
        build_type: [Debug, Release]

    steps:
    - name: Debug
      run: |
        echo GITHUB_SHA = ${{ env.GITHUB_SHA }}
        echo github.sha = ${{ github.sha }}

    - uses: actions/checkout@v2
    - uses: seanmiddleditch/gha-setup-ninja@v3

    - name: Setup NuGet Credentials
      shell: bash
      run: >
        nuget sources add
        -source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
        -storepasswordincleartext
        -name "GitHub"
        -username "${{ github.repository_owner }}"
        -password "${{ github.token }}"

    - uses: lukka/run-vcpkg@v10
      with:
        vcpkgGitCommitId: 078f3e51efd5ea6072d0ba28d11baa946519a2ce

    - name: CMake - Configure
      run: |
        mkdir build
        cd build
        cmake -G Ninja \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -DCMAKE_TOOLCHAIN_FILE='${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake' \
          ../

    - name: CMake - Build
      working-directory: build
      run: |
        cmake --build . --config ${{ matrix.build_type }}


  registry-update:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: PazerOP/vcpkg-registry-update@HEAD
      with:
        port-name: mh-glad2-gl
        workflow-pat: ${{ secrets.WORKFLOW_PAT }}

